"""student, teacher models

Revision ID: 32f1d01e1170
Revises: 5a29eb4e8832
Create Date: 2024-11-05 21:28:09.728051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32f1d01e1170'
down_revision: Union[str, None] = '5a29eb4e8832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson')
    op.drop_table('user_account')
    op.alter_column('reschedule', 'start_time',
               existing_type=sa.TIME(),
               nullable=False)
    op.alter_column('reschedule', 'end_time',
               existing_type=sa.TIME(),
               nullable=False)
    op.drop_constraint(None, 'reschedule', type_='foreignkey')
    op.create_foreign_key(None, 'reschedule', 'student', ['user_id'], ['id'])
    op.alter_column('restricted_time', 'start_time',
               existing_type=sa.TIME(),
               nullable=False)
    op.alter_column('restricted_time', 'end_time',
               existing_type=sa.TIME(),
               nullable=False)
    op.drop_constraint(None, 'restricted_time', type_='foreignkey')
    op.create_foreign_key(None, 'restricted_time', 'student', ['user_id'], ['id'])
    op.drop_constraint(None, 'scheduled_lesson', type_='foreignkey')
    op.create_foreign_key(None, 'scheduled_lesson', 'student', ['user_id'], ['id'])
    op.add_column('student', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.alter_column('student', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('student', 'teacher_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_foreign_key(None, 'student', 'user', ['user_id'], ['id'])
    op.drop_column('student', 'is_banned')
    op.drop_column('student', 'first_name')
    op.drop_column('student', 'is_premium')
    op.drop_column('student', 'user_name')
    op.drop_column('student', 'role')
    op.drop_column('student', 'second_name')
    op.add_column('teacher', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'teacher', 'user', ['user_id'], ['id'])
    op.drop_column('teacher', 'telegram_id')
    op.drop_column('teacher', 'name')
    op.drop_column('teacher', 'work_end')
    op.drop_column('teacher', 'work_start')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('work_start', sa.TIME(), nullable=False))
    op.add_column('teacher', sa.Column('work_end', sa.TIME(), nullable=False))
    op.add_column('teacher', sa.Column('name', sa.VARCHAR(length=64), nullable=False))
    op.add_column('teacher', sa.Column('telegram_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'user_id')
    op.add_column('student', sa.Column('second_name', sa.TEXT(), nullable=True))
    op.add_column('student', sa.Column('role', sa.VARCHAR(length=13), nullable=False))
    op.add_column('student', sa.Column('user_name', sa.TEXT(), nullable=True))
    op.add_column('student', sa.Column('is_premium', sa.BOOLEAN(), nullable=False))
    op.add_column('student', sa.Column('first_name', sa.TEXT(), nullable=True))
    op.add_column('student', sa.Column('is_banned', sa.BOOLEAN(), nullable=False))
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.alter_column('student', 'teacher_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('student', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('student', 'user_id')
    op.drop_constraint(None, 'scheduled_lesson', type_='foreignkey')
    op.create_foreign_key(None, 'scheduled_lesson', 'user_account', ['user_id'], ['id'])
    op.drop_constraint(None, 'restricted_time', type_='foreignkey')
    op.create_foreign_key(None, 'restricted_time', 'user_account', ['user_id'], ['id'])
    op.alter_column('restricted_time', 'end_time',
               existing_type=sa.TIME(),
               nullable=True)
    op.alter_column('restricted_time', 'start_time',
               existing_type=sa.TIME(),
               nullable=True)
    op.drop_constraint(None, 'reschedule', type_='foreignkey')
    op.create_foreign_key(None, 'reschedule', 'user_account', ['user_id'], ['id'])
    op.alter_column('reschedule', 'end_time',
               existing_type=sa.TIME(),
               nullable=True)
    op.alter_column('reschedule', 'start_time',
               existing_type=sa.TIME(),
               nullable=True)
    op.create_table('user_account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('telegram_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), nullable=False),
    sa.Column('telegram_username', sa.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('lesson',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
