"""add username

Revision ID: 5a29eb4e8832
Revises: 8c177dcb9394
Create Date: 2024-09-15 18:42:29.989178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a29eb4e8832'
down_revision: Union[str, None] = '8c177dcb9394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('telegram_username', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'telegram_username')
    # ### end Alembic commands ###
