"""add models

Revision ID: 80e1639bfbdd
Revises: 964ae9c0669c
Create Date: 2026-08-26 20:41:24.793783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80e1639bfbdd'
down_revision: Union[str, Sequence[str], None] = '964ae9c0669c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('notification_lesson', sa.Integer(), nullable=True),
    sa.Column('notification_homework', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('student_profile_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('student_profile_pkey')),
    sa.UniqueConstraint('student_id', name=op.f('student_profile_student_id_key'))
    )
    op.create_table('teacher_profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('work_start', sa.Time(), nullable=True),
    sa.Column('work_end', sa.Time(), nullable=True),
    sa.Column('lesson_length', sa.Integer(), nullable=False),
    sa.Column('between_lessons_break', sa.Integer(), nullable=False),
    sa.Column('max_lessons_per_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], name=op.f('teacher_profile_teacher_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('teacher_profile_pkey')),
    sa.UniqueConstraint('teacher_id', name=op.f('teacher_profile_teacher_id_key'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('teacher_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('notification_lessons_today', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('user_teacher_id_fkey'), 'user', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_teacher_id_fkey'), type_='foreignkey')
        batch_op.drop_column('notification_lessons_today')
        batch_op.drop_column('timezone')
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('role')

    op.drop_table('teacher_profile')
    op.drop_table('student_profile')
    # ### end Alembic commands ###
