"""events

Revision ID: 65fa8193a492
Revises: 80e1639bfbdd
Create Date: 2026-09-01 03:15:46.229382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65fa8193a492'
down_revision: Union[str, Sequence[str], None] = '80e1639bfbdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('event_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('event_pkey'))
    )
    op.create_table('recurrent_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('interval_end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('recurrent_event_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recurrent_event_pkey'))
    )
    op.create_table('recurrent_cancels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recurrent_event_id', sa.Uuid(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recurrent_event_id'], ['recurrent_event.id'], name=op.f('recurrent_cancels_recurrent_event_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recurrent_cancels_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurrent_cancels')
    op.drop_table('recurrent_event')
    op.drop_table('event')
    # ### end Alembic commands ###
