"""Homeworks

Revision ID: cc2782a9b737
Revises: d7e4a1874856
Create Date: 2025-09-02 16:31:18.206916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc2782a9b737'
down_revision: Union[str, Sequence[str], None] = 'd7e4a1874856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homeworks',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('executor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['executor_id'], ['executors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homeworks')
    # ### end Alembic commands ###
