START = "Приветственное сообщение"
HELP = "Помощь"
ADD_LESSON = "Добавить урок"
REMOVE_LESSON = "Отменить урок"
GET_SCHEDULE = "Расписание на сегодня"
GET_SCHEDULE_WEEK = "Расписание на неделю"
CANCEL = "Отмена"
ADMIN_GROUP = "О, админ!"
