"""add_token_to_user

Revision ID: 702da69e9f13
Revises: 14c5da11f604
Create Date: 2026-01-16 15:34:15.746565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '702da69e9f13'
down_revision: Union[str, None] = '14c5da11f604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.String(length=255), nullable=True))
    op.alter_column('users', 'telegram_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_users_token'), 'users', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_token'), table_name='users')
    op.alter_column('users', 'telegram_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users', 'token')
    # ### end Alembic commands ###
