"""add_tokens_and_history

Revision ID: 167fb78c6875
Revises: 52aeb7fd098c
Create Date: 2026-01-18 15:02:43.148483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167fb78c6875'
down_revision: Union[str, None] = '52aeb7fd098c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_tokens'))
    )
    op.create_index(op.f('ix_user_tokens_token'), 'user_tokens', ['token'], unique=True)
    op.add_column('users', sa.Column('invite_code', sa.String(length=25), nullable=True))
    op.drop_index(op.f('ix_users_token'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_invite_code'), 'users', ['invite_code'])
    op.drop_column('users', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('uq_users_invite_code'), 'users', type_='unique')
    op.create_index(op.f('ix_users_token'), 'users', ['token'], unique=True)
    op.drop_column('users', 'invite_code')
    op.drop_index(op.f('ix_user_tokens_token'), table_name='user_tokens')
    op.drop_table('user_tokens')
    # ### end Alembic commands ###
