"""Add teacher-student relation

Revision ID: 84455f771339
Revises: 673b04986503
Create Date: 2026-07-29 15:35:01.455580

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '84455f771339'
down_revision = '673b04986503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('teacher_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['teacher_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'teacher_id')
    # ### end Alembic commands ###
